d <- read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors = FALSE, header = TRUE)
d$Date <- dmy(d$Date)
d <- tbl_df(d)
ds <- filter(d, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
ds$Global_active_power = as.numeric(ds$Global_active_power)
hist(ds$Global_active_power, col = "red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power", xlim = c(0,8), xaxt = "n")
axis(at = c(0,2,4,6), labels = c("0","2","4","6"), side = 1)
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()